---
title: "Process_1_Download_MTBS_data"
author: "Jianning Ren"
date: "8/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=F, message=F, results="hold", fig.width=14, fig.height=10)
```

## source the R code for downloading data
## https://github.com/mbjoseph/mtbs-data



```{r}

install.packages('RNRCS')

library(RNRCS)

```


```{r}
grabNRCS.elements(site_id = "SCAN:1258")

snotel1 = grabNRCS.data(site_id = 1258, timescale = "daily", network = "SNTL", DayBgn = '2014-07-01', DayEnd = '2020-12-01')

```


## gauge 977

```{r}

grabNRCS.elements(site_id = "SCAN:977")

snotel2 = grabNRCS.data(site_id = 977, timescale = "daily", network = "SNTL", DayBgn = '1999-07-01', DayEnd = '2020-12-01')
snotel2.bk = snotel2

```


```{r}

head(snotel2)
names(snotel2) <- c("date","Tavg", "Tmax","Tmin","Tstart","Precip", "SnowDepth","SWE")
head(snotel2)
summary(snotel2)
snotel2 = snotel2 %>% mutate(date = as.Date(date)) %>% 
  filter(date >= as.Date("2000-01-01"))

# find the na data
na.index = which(is.na(snotel2$Tmin))
snotel2[na.index,]

```

## plot these results

```{r}

plot(snotel2$date, snotel2$SWE, type="l")

head(snotel2)
## convert the unit
# change the unit degree and inch to mm
snotel22 <-snotel2 %>% mutate(pre_mm=Precip*25.4) %>%
  mutate(SWE_mm=SWE*25.4) %>% ## inch to mm, it is 25.4 not 25,4
  mutate(Tmax_C=(Tmax-32)*5/9) %>%
  mutate(Tmin_C=(Tmin-32)*5/9) %>%
  mutate(Tave_C=(Tavg-32)*5/9) %>% 
  mutate(Tstart_C= (Tstart -32)*5/9) %>% 
  mutate(snow_depth = SnowDepth*25.4)


plot(snotel22$date, snotel22$Tmax_C, type ="l")


## seems like there are some anomlies big data

removeAnomaly = function(input, i.max, i.min) {
  
  anomaly.index = which(input > i.max | input < i.min)
  input[anomaly.index] <- NA
  input[anomaly.index] <- approx(input, xout = anomaly.index, method = "linear")$y
  return(input)
  
}

test = removeAnomaly(snotel22$Tave_C, 40, -30)

snotel22 <- snotel22 %>% 
  mutate(Tmax_C =  removeAnomaly(snotel22$Tmax_C, 40, -30)) %>% 
  mutate(Tave_C = removeAnomaly(snotel22$Tave_C, 40, -30)) %>% 
  mutate(Tmin_C = removeAnomaly(snotel22$Tmin_C, 40, -30)) %>% 
  mutate(Tstart = removeAnomaly(snotel22$Tstart, 40, -30)) %>% 
  mutate(precip_flux = c(0, diff(pre_mm))) %>% 
  mutate(precip_flux = ifelse(precip_flux<0, 0, precip_flux))

 plot(snotel22$date, snotel22$snow_depth, type='l')

```


## calculate the yearly

```{r}

snotel22.year.mean = snotel22 %>% 
   mutate(year = lubridate::year(date)) %>% 
  mutate(month = lubridate::month(date)) %>% 
  mutate(day = lubridate::day(date)) %>% 
  group_by(year) %>% 
  summarise_if(is.numeric, mean, na.rm=T) %>% 
  as.data.frame()

snotel22.year.sum = snotel22 %>% 
   mutate(year = lubridate::year(date)) %>% 
  mutate(month = lubridate::month(date)) %>% 
  mutate(day = lubridate::day(date)) %>% 
  group_by(year) %>% 
  summarise_if(is.numeric, sum, na.rm=T) %>% 
  as.data.frame()

summary(snotel22.year.sum)


```


## plot these result

```{r, fig.height=12, fig.width=28}
final.data = snotel22.year.mean %>% 
  dplyr::select(year, SWE_mm, Tmax_C, Tmin_C, Tave_C, snow_depth) %>% 
  mutate(precip = snotel22.year.sum$precip_flux) %>% 
  as.data.frame() %>% 
  filter(year<=2019)

plot.data = reshape::melt(final.data, id.vars="year")

ggplot(plot.data) +
  geom_line(aes(x =year, y=value), lwd=1.2)+
   facet_wrap(~variable, scales="free")+
   scale_x_continuous(breaks=scales::pretty_breaks(n = 10), limits = c(2000, 2020))+
  plot.theme3

```




## below is for plot


```{r}

library(ggplot2)
plot.theme3 <- theme(
  
  ## axis
  axis.text  = element_text(color = 'black', size = 20,face="bold"), ## control the axis numbers
  axis.title = element_text(size =20,face="bold"),
  axis.ticks = element_line(color = 'black'),
  axis.text.x = element_text(angle = 0, vjust = -0.5),
  axis.line.x = element_line(color = "black"),
  axis.line.y = element_line(color = "black"),
  axis.title.x = element_text(vjust=-5),
  axis.title.y = element_text(vjust= 4),
  

  ## legend
  ## legend.margin=margin(t=1, r=0, b=-0.5, l=0, unit="cm") control xlab and legend spacing
  legend.key.size = unit(1.5, "lines"),
  legend.key.width = unit(1.5, "cm"),
  legend.title = element_text(size = 20,face="bold"), # control the legend
  legend.text = element_text(size = 20,face="bold"),
  legend.spacing.x = unit(0.5, 'cm'),
  legend.key= element_rect(colour = "transparent", fill = "transparent"),
  legend.background = element_rect(fill = "transparent", colour = NA),
  legend.box.background = element_rect(fill = "transparent", colour = NA), ## this the control??
  
  
  # panel.background  = element_blank(),
  # 
  # panel.grid.major  = element_line(colour = "grey90", size = 0.5, linetype = 'dashed'),
  #legend.background = element_rect(fill = NA),panel.border = element_blank(),
  #panel.background  = element_blank(),

  #panel.grid.minor.x = element_blank(),
  #panel.grid.minor.y = element_blank(),
  #panel.ontop = TRUE,
  strip.text=element_text(size=20,face="bold"),
 # plot.margin = unit(c(0.6,1,0.6,1), "cm"),  ## control the plot area margin 1 is bottom, left, top, right
   
   plot.margin = unit(c(1,1,1.1,1), "cm"),
  
  plot.title=element_text(size = 22,face="bold",hjust = 0.5) # plot title
)

```